services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: checkraka-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: checkraka
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./Server/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - checkraka-network

  # Backend API Server
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: checkraka-backend
    restart: unless-stopped
    environment:
      PORT: 3000
      MONGO_DB_URL: mongodb://admin:password@mongodb:27017/checkraka?authSource=admin
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./Server:/app
      - /app/node_modules
    networks:
      - checkraka-network

  # Frontend React App
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: checkraka-frontend
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: http://localhost:3000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - checkraka-network

volumes:
  mongodb_data:

networks:
  checkraka-network:
    driver: bridge
